on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: npm install
        run: npm ci

      - name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v6.5
        with:
          config_path: ".eslintrc.json"

  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: npm install
        run: npm ci

      - name: Run Prettier
        run: npx prettier 'src/**/*.ts' --check --config .prettierrc.json
